site_name: OpenWaterLab (OWL)
site_description: Free and open-source tools for water system modelling, simulation, and analysis
site_url: https://openwaterlab.github.io/
repo_url: https://github.com/OpenWaterLab/openwaterlab.github.io
repo_name: OpenWaterLab/openwaterlab.github.io

theme:
  name: material
  logo: assets/OWL.svg
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - navigation.tabs
    - toc.follow
    - content.code.copy
  palette:
    - scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to darj mode

    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - fenced_code
  - attr_list

nav:
  - Home: index.md
  - OpenWaterLab(OWL):
      - About: about/index.md
      - Overview: about/overview.md
      - Contributing: about/contributing.md
      - License: about/license.md
  - Packages:
      - owl-data: packages/owl-data/index.md
      - owl-twin: packages/owl-twin/index.md
      - owl-wrrf: packages/owl-wrrf/index.md
      - owl-ont: packages/owl-ont/index.md
